print("Deme 3 numeros")
var1 = int(input("Valor 1 "))
var2 = int(input("Valor 2 "))
var3 = int(input("Valor 3 "))
print("Los numeros son: ",var1 ,var2 ,var3)
maximo = max(var1,var2,var3)
minimo = min(var1,var2,var3)
print("Este es el minimo: " ,minimo)
print("Este es el maximo: " ,maximo)